version: '3.8'

services:
  frontend:
    image: my-frontend
    ports:
      - "8080:80"

  backend:
    image: my-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
