# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "8080:80"

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_ENV=development
# frontend-backend-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - wind-power-network  # 连接同一网络
    depends_on:
      - backend

  backend:
    build:
      context: ..  # 修改构建上下文为项目根目录
      dockerfile: wind-power-forecast/backend/Dockerfile  # 使用相对于项目根目录的Dockerfile路径
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=kingbase       # 使用金仓数据库服务名称
      - DB_PORT=54321          # 金仓数据库端口
      - DB_USER=system         # 金仓默认用户
      - DB_PASSWORD=12345678ab # 金仓默认密码
      - DB_NAME=windpower      # 连接到windpower数据库
      - MINIO_ENDPOINT=minio   # 使用MinIO服务名称
      - MINIO_PORT=9000
    
    networks:
      - wind-power-network  # 连接同一网络
    depends_on:
      kingbase:
        condition: service_started  # 修改为service_started，不检查健康状态
      minio:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kingbase:
    image: kingbase_v009r001c002b0014_single_x86:v1
    container_name: wind-power-kingbase
    privileged: true  # 必须添加，否则会有权限问题
    environment:
      - NEED_START=yes
      - DB_USER=system  # 金仓默认用户
      - DB_PASSWORD=12345678ab  # 金仓默认密码
      - DB_MODE=oracle  # 使用oracle模式，这是金仓推荐的模式
      - ENCODING=UTF8
    volumes:
      - kingbase_data:/home/kingbase/userdata/  # 注意这里的路径
    ports:
      - "54321:54321"  # 金仓数据库默认端口为54321
    restart: unless-stopped
    networks:
      - wind-power-network
    command: /usr/sbin/init  # 必须使用此命令启动
    healthcheck:
      test: ["CMD", "ls", "/home/kingbase/userdata/data"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio
    container_name: wind-power-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data  # 使用命名卷
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - wind-power-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: wind-power-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      kingbase:
        condition: service_started  # 修改为service_started，不检查健康状态
    restart: unless-stopped
    networks:
      - wind-power-network
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:  # 声明命名卷
  kingbase_data:
  minio_data:
  pgadmin_data:

networks:
  wind-power-network:
    driver: bridge