# 已更新的local-images.yaml，适用于云服务器部署

services:
  frontend:
    image: wind-power-forecast-frontend:latest
    ports:
      - "8080:80"
    networks:
      - wind-power-network
    depends_on:
      - backend

  backend:
    image: wind-power-forecast-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=kingbase       # 修改为金仓数据库
      - DB_PORT=54321          # 金仓数据库端口
      - DB_USER=system         # 金仓默认用户
      - DB_PASSWORD=12345678ab # 金仓默认密码
      - DB_NAME=windpower      # 数据库名
      - MINIO_ENDPOINT=minio   
      - MINIO_PORT=9000
    networks:
      - wind-power-network
    depends_on:
      kingbase:
        condition: service_started  # 金仓数据库不支持健康检查，使用service_started
      minio:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kingbase:
    image: kingbase_v009r001c002b0014_single_x86:v1
    container_name: wind-power-kingbase
    privileged: true  # 金仓数据库需要特权模式
    environment:
      - NEED_START=yes
      - DB_USER=system
      - DB_PASSWORD=12345678ab
      - DB_MODE=oracle  # 金仓数据库推荐使用oracle模式
      - ENCODING=UTF8
    volumes:
      - kingbase_data:/home/kingbase/userdata/
    ports:
      - "54321:54321"
    restart: unless-stopped
    networks:
      - wind-power-network
    command: /usr/sbin/init

  minio:
    image: minio/minio:latest
    container_name: wind-power-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - wind-power-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wind-power-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      kingbase:
        condition: service_started
    restart: unless-stopped
    networks:
      - wind-power-network
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  kingbase_data:  # 修改为金仓数据卷
    name: wind-power-kingbase-data
  minio_data:
    name: wind-power-minio-data
  pgadmin_data:
    name: wind-power-pgadmin-data

networks:
  wind-power-network:
    driver: bridge