import pandas as pd
from flask import Blueprint, request, jsonify, current_app
from werkzeug.utils import secure_filename
import os
import io
from datetime import datetime

from db_session import db_session
from db_models import TrainPreMiddle, TrainPreShort # Import the new models
from services.file_service import allowed_file # Reuse existing file validation if desired

feature_upload_bp = Blueprint('feature_upload', __name__)

# Map table names to model classes
TABLE_MODEL_MAP = {
    'train_pre_middle': TrainPreMiddle,
    'train_pre_short': TrainPreShort
}

def map_csv_to_model(row_dict, model_class):
    """Maps a dictionary (from CSV row) to the SQLAlchemy model attributes."""
    mapped_data = {}
    # Direct mapping for standard columns (case-insensitive matching for Timestamp)
    for key, value in row_dict.items():
        if key.lower() == 'timestamp':
            try:
                # Attempt to parse various timestamp formats
                mapped_data['Timestamp'] = pd.to_datetime(value) 
            except Exception as e:
                current_app.logger.warning(f"Could not parse timestamp '{value}': {e}")
                mapped_data['Timestamp'] = None # Or raise error / handle differently
            break # Found timestamp, move on
            
    # Mapping for feature columns (needs to match the structure in features.py)
    # Assumes CSV headers are like "100u_23.8_103.2"
    for csv_col_name, value in row_dict.items():
        if csv_col_name.lower() != 'timestamp' and csv_col_name != 'record_id': # Skip timestamp and potential record_id in csv
             # Construct the expected Python attribute name (replace '.' with '_')
             # Note: This simple replacement might not be robust for all possible SQL column names
             # if they contain other special characters needing escaping in SQL but not Python.
             # Also, assumes the model attributes are defined like col_100u_23_8_103_2
            py_attr_name = f"col_{csv_col_name.replace('.', '_')}" 
            
            # Check if the model class actually has this attribute
            if hasattr(model_class, py_attr_name):
                 try:
                     # Convert to float, handle potential None/empty strings
                     mapped_data[py_attr_name] = float(value) if value not in [None, ''] else None
                 except (ValueError, TypeError) as e:
                     current_app.logger.warning(f"Could not convert feature '{csv_col_name}' value '{value}' to float: {e}")
                     mapped_data[py_attr_name] = None # Or raise an error

    return mapped_data


@feature_upload_bp.route('/api/upload_feature_csv', methods=['POST'])
def upload_feature_csv():
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400
    
    file = request.files['file']
    table_name = request.form.get('table_name')

    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400
        
    if not table_name or table_name not in TABLE_MODEL_MAP:
        return jsonify({"error": f"Invalid or missing 'table_name'. Must be one of: {list(TABLE_MODEL_MAP.keys())}"}), 400

    # Optional: Reuse allowed_file logic if needed
    # if not allowed_file(file.filename, current_app.config.get('ALLOWED_EXTENSIONS', {'.csv'})):
    #     return jsonify({"error": "Invalid file type. Only CSV allowed."}), 400

    if not file.filename.lower().endswith('.csv'):
         return jsonify({"error": "Invalid file type. Only CSV allowed."}), 400

    TargetModel = TABLE_MODEL_MAP[table_name]
    
    try:
        # Read CSV data into pandas DataFrame
        # Use io.BytesIO to read the file stream directly without saving
        csv_data = io.BytesIO(file.read())
        df = pd.read_csv(csv_data)
        
        # Basic validation: Check for Timestamp column (case-insensitive)
        if not any(col.lower() == 'timestamp' for col in df.columns):
             return jsonify({"error": "CSV must contain a 'Timestamp' column."}), 400

        inserted_count = 0
        error_count = 0
        errors = []
        
        with db_session() as session:
            # Iterate over DataFrame rows
            for index, row in df.iterrows():
                row_dict = row.to_dict()
                try:
                    # Map CSV row to model object dictionary
                    model_data = map_csv_to_model(row_dict, TargetModel)
                    
                    # Validate timestamp presence after mapping
                    if 'Timestamp' not in model_data or model_data['Timestamp'] is None:
                         raise ValueError(f"Row {index+1}: Could not parse Timestamp or Timestamp missing.")

                    # Create model instance - **record_id** is auto-generated by DB
                    # Ensure only columns present in the model are passed
                    valid_model_keys = {k for k in model_data if hasattr(TargetModel, k)}
                    filtered_model_data = {k: model_data[k] for k in valid_model_keys}

                    db_object = TargetModel(**filtered_model_data) 
                    session.add(db_object)
                    inserted_count += 1
                    
                    # Optional: Commit in batches for very large files
                    # if inserted_count % 1000 == 0:
                    #     session.commit()
                    #     current_app.logger.info(f"Committed batch of 1000 records to {table_name}")

                except Exception as e:
                    error_count += 1
                    errors.append(f"Row {index + 1}: {str(e)}")
                    session.rollback() # Rollback changes for the failed row or batch
                    current_app.logger.error(f"Error processing row {index + 1} for {table_name}: {e}")
                    # Optional: Stop processing after too many errors
                    # if error_count > 100:
                    #    raise Exception("Too many errors during CSV processing.")
                       
            if error_count == 0:
                session.commit() # Commit remaining records or the whole transaction
                current_app.logger.info(f"Successfully inserted {inserted_count} records into {table_name}")
                return jsonify({
                    "message": f"Successfully uploaded and inserted {inserted_count} records into {table_name}.",
                    "inserted_count": inserted_count
                }), 200
            else:
                 # Even with errors, maybe some rows were processed before the first error if not batching/rolling back full transaction
                 # Decide if partial success is acceptable or if the whole operation should fail.
                 # Current logic with rollback per row error means only failed rows are skipped.
                 session.commit() # Commit successfully processed rows
                 current_app.logger.warning(f"Completed processing for {table_name} with {error_count} errors.")
                 return jsonify({
                     "warning": f"Processed file with {error_count} errors.",
                     "inserted_count": inserted_count, # Rows inserted before errors or between errors
                     "error_count": error_count,
                     "errors": errors[:50] # Limit returned errors
                 }), 207 # Multi-Status

    except pd.errors.EmptyDataError:
        return jsonify({"error": "CSV file is empty."}), 400
    except Exception as e:
        current_app.logger.error(f"Failed to process CSV upload for {table_name}: {e}", exc_info=True)
        return jsonify({"error": f"An unexpected error occurred: {str(e)}"}), 500 