name: wind-power-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  - flask
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - lightgbm
  - pip:
      - async-timeout==5.0.1
      - bcrypt==4.2.1
      - bidict==0.23.1
      - blinker==1.9.0
      - cffi==1.17.1
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.0
      - cryptography==44.0.0
      - cycler==0.12.1
      - dnspython==2.7.0
      - eventlet==0.38.0
      - flask-cors==3.0.10
      - flask-socketio==5.4.1
      - fonttools==4.55.1
      - greenlet==3.1.1
      - gunicorn==20.1.0
      - h11==0.14.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - paramiko==3.5.0
      - pillow==11.0.0
      - pycparser==2.22
      - pynacl==1.5.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - python-engineio==4.10.1
      - python-socketio==5.11.4
      - pytz==2024.2
      - redis==4.5.5
      - schedule==1.2.2
      - scipy==1.13.1
      - simple-websocket==1.1.0
      - six==1.16.0
      - threadpoolctl==3.5.0
      - tzdata==2024.2
      - werkzeug==2.3.4
      - wsproto==1.2.0
      - zipp==3.21.0
