version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wind-power-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yzz0216yh
      POSTGRES_DB: windpower
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 使用命名卷
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - wind-power-network

  minio:
    image: minio/minio
    container_name: wind-power-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data  # 使用命名卷
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - wind-power-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: wind-power-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - wind-power-network

volumes:  # 声明命名卷
  postgres_data:
  minio_data:

networks:
  wind-power-network:
    driver: bridge